replicaCount: 2
image:
  repository: my-app
  tag: "latest"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  hosts:
    - host: my-app.example.com
      paths:
        - /
