- name: Initialize and Secure Hosts
  hosts: all
  vars_files:
    - ../../vars/vault.yml
  roles:
    - ../../roles/k8s-dependencies
    - ../../roles/vpn
    - ../../roles/wireguard-ui
    - ../../roles/security
    - ../../roles/rke-setup
    - ../../roles/rancher-agent
    - ../../roles/nginx-ingress
