- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: true
  become: yes
