- name: Install WireGuard
  apt:
    name: wireguard
    state: present
  become: yes

- name: Check if WireGuard private key exists
  stat:
    path: /etc/wireguard/privatekey
  register: wg_private_key

- name: Generate WireGuard private and public keys
  shell: |
    umask 077
    wg genkey > /etc/wireguard/privatekey
    cat /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
  args:
    creates: /etc/wireguard/privatekey
  become: yes
  when: not wg_private_key.stat.exists

- name: Validate WireGuard private key
  shell: |
    wc -c < /etc/wireguard/privatekey
  register: privatekey_validation
  failed_when: privatekey_validation.stdout | int != 45
  become: yes

- name: Read WireGuard private key
  slurp:
    src: /etc/wireguard/privatekey
  register: private_key_content
  become: yes

- name: Fetch public key of current node
  shell: cat /etc/wireguard/publickey
  register: current_node_public_key
  become: yes

- name: Collect public key and IP for VPN configuration
  set_fact:
    vpn_config:
      public_key: "{{ current_node_public_key.stdout.strip() }}"
      ip: "{{ ansible_host | default(inventory_hostname) }}"

- name: Collect all nodes' public keys
  add_host:
    name: "{{ inventory_hostname }}"
    public_key: "{{ current_node_public_key.stdout.strip() }}"
    private_key_decoded: "{{ private_key_content.content | b64decode }}"
    ansible_host: "{{ ansible_host | default(inventory_hostname) }}"
  become: no
  changed_when: false

- name: Set private key variable
  set_fact:
    private_key_decoded: "{{ private_key_content.content | b64decode }}"
    
# Server-specific tasks
- name: Configure WireGuard as VPN server
  template:
    src: ../../files/wireguard_interface.j2
    dest: /etc/wireguard/wg0.conf
  become: yes
  when: "'rancher' in group_names"
  vars:
    peers: >
      {{ groups['vps'] | map('extract', hostvars, ['current_node_public_key', 'ansible_host']) | list }}

- name: Check if WireGuard interface is active
  command: ip link show wg0
  register: wg_interface_status
  failed_when: false
  changed_when: false

- name: Bring down WireGuard interface if active
  command: wg-quick down wg0
  become: yes
  when: wg_interface_status.rc == 0

- name: Start WireGuard server
  command: "wg-quick up wg0"
  become: yes
  when: "'rancher' in group_names"

# Client-specific tasks
- name: Configure WireGuard as VPN client
  template:
    src: ../../files/wireguard_peer.j2
    dest: /etc/wireguard/wg0.conf
  become: yes
  when: "'rancher' not in group_names"
  vars:
    server_public_key: "{{ hostvars[groups['rancher'][0]]['current_node_public_key'].stdout.strip() }}"
    vpn_server_ip: "{{ hostvars[groups['rancher'][0]]['ansible_host'] }}"


- name: Start WireGuard client
  command: "wg-quick up wg0"
  become: yes
  when: "'rancher' not in group_names"
